# Generated by Django 4.2.17 on 2025-02-02 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('authorid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookcategories',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bookcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookgenres',
            fields=[
                ('genreid', models.AutoField(primary_key=True, serialize=False)),
                ('genrename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bookgenres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookloans',
            fields=[
                ('loanid', models.AutoField(primary_key=True, serialize=False)),
                ('loandate', models.DateTimeField()),
                ('returndate', models.DateTimeField(blank=True, null=True)),
                ('isreturned', models.BooleanField(blank=True, null=True)),
                ('renewalscount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookloans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publicationyear', models.IntegerField(blank=True, null=True)),
                ('totalcopies', models.IntegerField()),
                ('availablecopies', models.IntegerField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('fineid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ispaid', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paymentmethods',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('cardnumber', models.CharField(max_length=16)),
                ('expirydate', models.DateField()),
                ('cvv', models.IntegerField()),
            ],
            options={
                'db_table': 'paymentmethods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('reviewtext', models.CharField(blank=True, max_length=1000, null=True)),
                ('reviewdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userlogs',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'userlogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('passwordhash', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookcategorymapping',
            fields=[
                ('bookid', models.OneToOneField(db_column='bookid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.books')),
            ],
            options={
                'db_table': 'bookcategorymapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookgenremapping',
            fields=[
                ('bookid', models.OneToOneField(db_column='bookid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.books')),
            ],
            options={
                'db_table': 'bookgenremapping',
                'managed': False,
            },
        ),
    ]
